### ISSUE TITLE
Cannot build with MQTTOnlyBSDSocket set to 0

### ISSUE THREAD

**Issue by juhda** [X-Ryl669/eMQTT5#1]
Cannot build when setting the value of `MQTTOnlyBSDSocket` to `0` in `lib/include/Network/Clients/MQTT.hpp` because `lib/src/Network/Clients/MQTTClient.cpp` tries to include files that do not exist in the repository.

**Comment by X-Ryl669** [comment]
Yes that's true. Those files are part of a very large networking multi-protocol library that we use internally for our needs and it's not open source (yet ?).

You have to define `MQTTOnlyBSDSocket` to `1`. If you need TLS, you'll need to download and use `MbedTLS` library in that case. For an example code, you have [the related repository](https://github.com/X-Ryl669/esp-eMQTT5)

**Comment by X-Ryl669** [comment]
The code will build and work correctly with `MQTTOnlyBSDSocket` set to `1`, I meant.

**Comment by juhda** [comment]
I understand. Thank you for the clarification.

We have a scenario when our application is compiled with Visual Studio, in which case BSD sockets are not available. That's why I started to look around in the code and tried to change the macro; I hoped it might help.
Is there any straightforward solution to build with Visual Studio?

**Comment by X-Ryl669** [comment]
Do you need SSL ?

Currently, I can easily add the missing `Socket.hpp` file but `SSLSocket.hpp` requires so much dependencies (mainly OpenSSL wrappers but also all crypto code that have nothing to do with this project). 

I'm sorry I'm not using Windows anymore since many years. I know the `Socket` class is cross platform, but I don't know for `SSLSocket` status.

**Comment by juhda** [comment]
No need for SSL (currently).

**Comment by juhda** [comment]
Looks good. Thank you very much!
